Add some helpers to makefile

diff --git a/mqtt-pipeline-controller/Makefile b/mqtt-pipeline-controller/Makefile
--- a/mqtt-pipeline-controller/Makefile
+++ b/mqtt-pipeline-controller/Makefile
@@ -1,3 +1,16 @@
+SHELL=/bin/bash
+JSONNET_FMT=--indent 2 --string-style s --comment-style s --no-pad-arrays --pad-objects --pretty-field-names
+
+TEST_JSONNET=$(wildcard ./tests/*.jsonnet)
+CODE_JSONNET=$(wildcard ./jsonnet/*.jsonnet)
+
+ALL_JSONNET=$(TEST_JSONNET) $(CODE_JSONNET)
+
+PHONY_GOLDEN=$(patsubst %.jsonnet,%-golden.json,$(TEST_JSONNET))
+PHONY_DIFF=$(patsubst %.jsonnet,%.diff,$(TEST_JSONNET))
+PHONY_PARSE=$(patsubst %.jsonnet,%.parse,$(ALL_JSONNET))
+
+
 PWD := ${CURDIR}
 
 imageTag = 0.1
@@ -35,3 +48,53 @@ push_mqtt_subscriber: image_mqtt_subscriber
 
 
 push: push_controller push_mqtt_publisher push_mqtt_subscriber
+
+test: lint parse diff
+
+.PHONY: unittests lint diff %.parse %.diff %-golden.json diff-help fix-lint gen-golden regen-golden delete-golden
+
+lint:
+	@set -e; errs=0; \
+     for f in $(ALL_JSONNET) $(LIB_JSONNET); do \
+   JSONNETFMTCMD=$$(command -v jsonnetfmt || echo "jsonnet fmt"); \
+     if ! $$JSONNETFMTCMD --test $(JSONNET_FMT) -- $$f; then \
+      echo "FAILED lint: $$f" >&2; \
+      errs=$$(( $$errs + 1 )); \
+    fi; \
+  done; \
+  if [ $$errs -gt 0 ]; then \
+    echo "NOTE: if the 'lint' target fails, run:"; \
+    echo "      $(MAKE) fix-lint lint"; \
+    exit 1; \
+  fi
+
+diff: diff-help $(PHONY_DIFF)
+
+%.diff: %.jsonnet
+	diff -u $(*)-golden.json <(jsonnet $(<))
+
+%.parse: %.jsonnet
+	jsonnet $(<) > /dev/null
+
+%-golden.json: %.jsonnet
+	jsonnet $(<) > $(@)
+
+diff-help:
+	@echo "NOTE: if the 'diff' target fails, review output and run:"
+	@echo "      $(MAKE) gen-golden diff"
+	@echo
+
+fix-lint:
+	@set -e; \
+	for f in $(ALL_JSONNET) $(LIB_JSONNET); do \
+	JSONNETFMTCMD=$$(command -v jsonnetfmt || echo "jsonnet fmt"); \
+	  echo $$JSONNETFMTCMD -i $(JSONNET_FMT) -- $$f; \
+	  jsonnetfmt -i $(JSONNET_FMT) -- $$f; \
+	done
+
+gen-golden: $(PHONY_GOLDEN)
+
+regen-golden: delete-golden gen-golden
+
+delete-golden:
+	@find . -name "*-golden.json" -delete
